name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 43.207.145.189 >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Ubuntu
        run: |
          ssh ubuntu@43.207.145.189 'cd /home/ubuntu/node.js/node.js_backend && git pull origin master && npm install && pm2 restart app.js'
