name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master  # Change this to your main branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and test your app (if needed)
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 43.207.145.189 >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Ubuntu
        run: |
          cd /home/ubuntu/node.js
          git pull origin main  # Pull the latest code from the 'main' branch
          npm install           # Install any new dependencies
          pm2 start app.js      # Start your Node.js app with PM2
