name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master  # Change this to your main branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and test your app (if needed)
        run: npm run build

      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.43.207.145.189 }}  # Use an environment variable for the server's IP
          username: ${{ secrets.ubuntu }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/node.js
            git pull origin master  # Pull the latest code
            npm install            # Install any new dependencies
            pm2 start app.js       # Start your Node.js app with PM2
